#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci_scripts/expect_scripts/shared-code.exp

spawn ./examples/AllSyntax/main

# 1. Used subst to evaluate \u00a0
# 2. Escaped glob brackets as \\[ and \\]
# 3. Did NOT escape { and }, as they are not special in glob
set expected_output [normalize_output [subst -nocommands -novariables {
Hello, world!
Hello, world! (using alias)
{ diff: 5, div: 2, div_trunc: 2, eq: False, gt: True, gteq: True, lt: False, lteq: False, neg: -10, neq: True, prod: 50, rem: 0, sum: 15 }
{ bool_and_keyword: False, bool_or_keyword: True, not_a: False }
"One Two"
"Three Four"
The color is red.
78
Success
Line 1
Line 2
Line 3
Unicode escape sequence: \u00a0
This is an effectful function!
Ok(1)
Err(NoFirstError(ListWasEmpty))
Err(NoFirstError(ListWasEmpty))
15.0
False
10.0
\\[dbg\\] 42.0
42.0
NotOneTwoNotFive
("Roc", 1.0)
\\["a", "b"\\]
("Roc", 1.0, 1.0, 1.0)
42
10.0
{ age: 31, name: "Alice" }
{ age: 30, name: "Alice" }
{ binary: 5.0, explicit_i128: 5, explicit_i16: 5, explicit_i32: 5, explicit_i64: 5, explicit_i8: 5, explicit_u128: 5, explicit_u16: 5, explicit_u32: 5, explicit_u64: 5, explicit_u8: 5, hex: 5.0, octal: 5.0, usage_based: 5.0 }
<opaque>
"The secret key is: my_secret_key"
False
99
"12345.0"
"Foo with 42 and hello"
"other color"
"Names: Alice, Bob, Charlie"
"A"
"other letter"
True
}]]

# Cleaned up block to explicitly handle match, early EOF, or timeout
expect {
    $expected_output {
        expect eof
        check_exit_and_segfault
    }
    eof {
        puts stderr "\nError: output was different from expected value (got EOF)."
        exit 1
    }
    timeout {
        puts stderr "\nError: timed out waiting for output."
        exit 1
    }
}
