#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci_scripts/expect_scripts/shared-code.exp

spawn ./examples/Arithmetic/main 20 4


expect "sum: 24\r\ndifference: 16\r\nproduct: 80\r\ninteger quotient: 5\r\nremainder: 0\r\nexponentiation: 160000" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1
