#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci_scripts/expect_scripts/shared-code.exp

spawn ./examples/CommandLineArgsFile/main examples/CommandLineArgsFile/input.txt 

expect "First line in file:\r\nMy candle burns at both ends;\r\n\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1