#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 30

source ./ci_scripts/expect_scripts/shared-code.exp

cd "./examples/DotNetPlatform/platform/"

spawn dotnet run

expect "Hello from .NET!\r\n" {
  expect "Hi from roc! (in a .NET platform) 🔥🦅🔥\r\n" {
    expect eof {
        check_exit_and_segfault
    }
  }
}

puts stderr "\nError: output was different from expected value."
exit 1
