#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci_scripts/expect_scripts/shared-code.exp

spawn ./examples/EncodeDecode/main

expect "ItemKind.(Text)\r\nItemKind.(Method)\r\nItemKind.(Function)\r\nItemKind.(Constructor)\r\nItemKind.(Field)\r\nItemKind.(Variable)\r\nItemKind.(Class)\r\nItemKind.(Interface)\r\nItemKind.(Module)\r\nItemKind.(Property)\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1