#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci_scripts/expect_scripts/shared-code.exp

spawn ./examples/EncodeDecode/main

expect "Text\r\nMethod\r\nFunction\r\nConstructor\r\nField\r\nVariable\r\nClass\r\nInterface\r\nModule\r\nProperty\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1