#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci_scripts/expect_scripts/shared-code.exp

spawn ./examples/ImportPackageFromModule/main

expect {
    -re {Ok\(\["h", "e", "l", "l", "o"\]\)\r\n} {
        expect eof {
            check_exit_and_segfault
        }
    }
    eof {
        puts stderr "\nError: output was different from expected value (got early EOF)."
        exit 1
    }
    timeout {
        puts stderr "\nError: timed out waiting for output."
        exit 1
    }
}