on:
  pull_request:
  workflow_dispatch:

name: Test examples without nix using alpha release

# this cancels workflows currently in progress if you start a new one
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# Do not add permissions here! Configure them at the job level!
permissions: {}

jobs:
  test-examples:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-22.04, ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-15]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
    
      - uses: roc-lang/setup-roc@68881a790d8281b2466c27e1955517e0c2f6bb6b

      - name: Run Roc
        run: roc version
        
      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.operating-system, 'ubuntu-')
        run: sudo apt install -y expect

      - name: Install dependencies (macOS)
        if: startsWith(matrix.operating-system, 'macos-')
        run: |
          brew install expect
          brew install z3

      - name: check if roc files are properly formatted
        run: ROC=./roc_alpha/roc ./ci_scripts/check_format.sh

      - run: ROC=./roc_alpha/roc ./ci_scripts/all_tests.sh

      - name: Checks if every folder in examples is mentioned in ./examples/index.md
        run: bash ./ci_scripts/check_index.sh
